# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorry.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from fileinput import close
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import qApp, QAction, QMessageBox
from PyQt5.QtGui import QIcon


class Sorrymywindow():
    
   def showdialog():
        msg = QMessageBox()
        msg.setWindowIcon(QIcon('img\icons8-грустно-48.png'))
        msg.setIcon(QMessageBox.Information)

        msg.setText("Information")
        msg.setInformativeText("We're sorry, but this feature is not yet available.")
        msg.setWindowTitle("Sorry")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.buttonClicked.connect(close)
        
        retval = msg.exec_()
       


