# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorry.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from fileinput import close
from typing_extensions import Self
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import qApp, QAction, QMessageBox, QInputDialog, QPushButton, QLineEdit, QDialog
from PyQt5.QtGui import QIcon




class Sorrymywindow():
    
   def showdialog():
      msg = QMessageBox()
      msg.setWindowIcon(QIcon('img\icons8-грустно-48.png'))
      msg.setIcon(QMessageBox.Information)
      msg.setMinimumSize(600, 250)

      msg.setText("Information")
      font = QtGui.QFont()
      font.setFamily("Segoe UI Semilight")
      font.setPointSize(10)
      msg.setFont(font)
      msg.setInformativeText("We're sorry, but this feature is not yet available.")
      msg.setWindowTitle("Sorry")
      msg.setStandardButtons(QMessageBox.Ok)
      msg.buttonClicked.connect(close)
        
      retval = msg.exec_()

class Dialog_New_Person():

   def __init__(self):
      super(Dialog_New_Person, self).__init__()
      self.ui = Dialog_New_Person()
      self.ui.dia_new_pers(self)
        
     
   def dia_new_pers(self):
      
      dia = QDialog()
      dia.setWindowIcon(QIcon('img\icons8-создать-новый-48.png'))
      dia.setWindowTitle("New Person")
      dia.setMinimumSize(400, 180)
      dia.gridLayout_1 = QtWidgets.QGridLayout(dia)
      dia.gridLayout_1.setAlignment(QtCore.Qt.AlignTop)
      dia.gridLayout_1.setObjectName("QVBoxLayout")
      dia.gridLayout_1.setSpacing(1)
      
      # Создание Строки First Name
      dia.first_name = QtWidgets.QLabel(dia)
      dia.first_name.setText("First Name")
      dia.first_name.setObjectName("first_name")
      dia.gridLayout_1.addWidget(dia.first_name, 0, 0)

      dia.first_name_line = QtWidgets.QLineEdit(dia)
      dia.first_name_line.setObjectName("first_name_line")
      dia.gridLayout_1.addWidget(dia.first_name_line, 0, 1)
      global first_name_pers
      first_name_pers = dia.first_name_line.text()
      
      
         
      
      
      
      
      # Создание Строки Last Name
      dia.last_name = QtWidgets.QLabel(dia)
      dia.last_name.setText("Last Name")
      dia.last_name.setObjectName("last_name")
      dia.gridLayout_1.addWidget(dia.last_name, 1, 0)

      dia.last_name_line = QtWidgets.QLineEdit(dia)
      dia.last_name_line.setObjectName("last_name_line")
      dia.gridLayout_1.addWidget(dia.last_name_line, 1, 1)

      # Создание строки Bithday
      dia.bithday = QtWidgets.QLabel(dia)
      dia.bithday.setObjectName("bithday")
      dia.bithday.setText("Age")
      dia.gridLayout_1.addWidget(dia.bithday, 2, 0)

      dia.bithday_line = QtWidgets.QLineEdit(dia)
      dia.gridLayout_1.addWidget(dia.bithday_line, 2, 1)
      

      # Создание radion Button
      dia.sex_label = QtWidgets.QLabel(dia)
      dia.sex_label.setText("Sex")
      dia.sex_label.setObjectName("sex_label")
      dia.gridLayout_1.addWidget(dia.sex_label, 3, 0)

      # M
      dia.rad_btn_male = QtWidgets.QRadioButton(dia)
      dia.rad_btn_male.setObjectName("rad_btn_male")
      dia.rad_btn_male.setText("Male")
      dia.gridLayout_1.addWidget(dia.rad_btn_male, 3, 1)

      # F
      dia.rad_btn_female = QtWidgets.QRadioButton(dia)
      dia.rad_btn_female.setObjectName("rad_btn_female")
      dia.rad_btn_female.setText("Female")
      dia.gridLayout_1.addWidget(dia.rad_btn_female, 4, 1)

      # Создание кнопки Save
      dia.btn_save = QtWidgets.QPushButton(dia)
      dia.btn_save.setText("Save")
      dia.btn_save.setObjectName("btn_save")
      dia.gridLayout_1.addWidget(dia.btn_save)
      sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
      sizePolicy.setHorizontalStretch(0)
      sizePolicy.setVerticalStretch(0)
      sizePolicy.setHeightForWidth(dia.btn_save.sizePolicy().hasHeightForWidth())
      dia.btn_save.setSizePolicy(sizePolicy)  
      dia.btn_save.clicked.connect(self.clik)
          

      


      # создание кнопки Cancel
      #dia.btn_cancel = QtWidgets.QPushButton(dia)
      #dia.btn_cancel.setText("Cancel")
      #dia.btn_cancel.setObjectName("btn_cancel")
      #dia.gridLayout_1.addWidget(dia.btn_cancel)
      #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
      #sizePolicy.setHorizontalStretch(0)
      #sizePolicy.setVerticalStretch(0)
      #sizePolicy.setHeightForWidth(dia.btn_cancel.sizePolicy().hasHeightForWidth())
      #dia.btn_cancel.setSizePolicy(sizePolicy)

      dia.exec_() 


   def clik(self):
         
      d = first_name_pers
        
      print(d)
           

     



# Создание кнопок испытуемых
class Button_isp():
   
   def __init__(self) -> None:
      pass

   def isp_buttom(self):
      self.btn_isp_1 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_1.setText(f'1. Егор')
      self.btn_isp_1.setObjectName("btn_isp_1") 
      self.verticalLayout.addWidget(self.btn_isp_1)

      self.btn_isp_2 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_2.setText(f'2) Егор')
      self.btn_isp_2.setObjectName("btn_isp_2") 
      self.verticalLayout.addWidget(self.btn_isp_2)

      self.btn_isp_3 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_3.setText(f'3) Егор')
      self.btn_isp_3.setObjectName("btn_isp_3") 
      self.verticalLayout.addWidget(self.btn_isp_3)

      self.btn_isp_4 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_4.setText(f'4) Егор')
      self.btn_isp_4.setObjectName("btn_isp_4") 
      self.verticalLayout.addWidget(self.btn_isp_4)

      self.btn_isp_5 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_5.setText(f'5) Егор')
      self.btn_isp_5.setObjectName("btn_isp_5") 
      self.verticalLayout.addWidget(self.btn_isp_5)

      self.btn_isp_6 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_6.setText(f'6) Егор')
      self.btn_isp_6.setObjectName("btn_isp_6") 
      self.verticalLayout.addWidget(self.btn_isp_6)

      self.btn_isp_7 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_7.setText(f'7) Егор')
      self.btn_isp_7.setObjectName("btn_isp_7") 
      self.verticalLayout.addWidget(self.btn_isp_7)

      self.btn_isp_8 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_8.setText(f'8) Егор')
      self.btn_isp_8.setObjectName("btn_isp_8") 
      self.verticalLayout.addWidget(self.btn_isp_8)

      self.btn_isp_9 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_9.setText(f'9) Егор')
      self.btn_isp_9.setObjectName("btn_isp_9") 
      self.verticalLayout.addWidget(self.btn_isp_9)

      self.btn_isp_10 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_10.setText(f'10) Егор')
      self.btn_isp_10.setObjectName("btn_isp_10") 
      self.verticalLayout.addWidget(self.btn_isp_10)

      self.btn_isp_11 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_11.setText(f'11) Егор')
      self.btn_isp_11.setObjectName("btn_isp_11") 
      self.verticalLayout.addWidget(self.btn_isp_11)

      self.btn_isp_12 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_12.setText(f'12) Егор')
      self.btn_isp_12.setObjectName("btn_isp_12") 
      self.verticalLayout.addWidget(self.btn_isp_12)

      self.btn_isp_13 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_13.setText(f'13) Егор')
      self.btn_isp_13.setObjectName("btn_isp_13") 
      self.verticalLayout.addWidget(self.btn_isp_13)

      self.btn_isp_14 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_14.setText(f'14) Егор')
      self.btn_isp_14.setObjectName("btn_isp_14") 
      self.verticalLayout.addWidget(self.btn_isp_14)

      self.btn_isp_15 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_15.setText(f'15) Егор')
      self.btn_isp_15.setObjectName("btn_isp_15") 
      self.verticalLayout.addWidget(self.btn_isp_15)

      self.btn_isp_16 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_16.setText(f'16) Егор')
      self.btn_isp_16.setObjectName("btn_isp_16") 
      self.verticalLayout.addWidget(self.btn_isp_16)

      self.btn_isp_17 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_17.setText(f'17) Егор')
      self.btn_isp_17.setObjectName("btn_isp_17") 
      self.verticalLayout.addWidget(self.btn_isp_17)

      self.btn_isp_18 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_18.setText(f'18) Егор')
      self.btn_isp_18.setObjectName("btn_isp_18") 
      self.verticalLayout.addWidget(self.btn_isp_18)

      self.btn_isp_19 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_19.setText(f'19) Егор')
      self.btn_isp_19.setObjectName("btn_isp_19") 
      self.verticalLayout.addWidget(self.btn_isp_19)

      self.btn_isp_20 = QtWidgets.QPushButton(self.scrollArea_Name)
      self.btn_isp_20.setText(f'20) Егор')
      self.btn_isp_20.setObjectName("btn_isp_20") 
      self.verticalLayout.addWidget(self.btn_isp_20)